### ISSUE TITLE
Option to log duplicate keys

### ISSUE THREAD

**Issue by fugerit79** [fugerit-org/snakeyaml#1]
Hello, thanks for the great work on snakeyaml project.

I’ve been using either direcly on maby of the projects I work and indirecly (for instance smallrye-config).

In some of the teams I partecipate, sometimes some not very disciplined developer entered some duplicate keys in yaml configurations.

As far as I understand, right now SnakeYAML has an all or nothing approach to duplicate keys (using LoadOpttions.isAllowDuplicateKeys()): either an exception is thrown or they are totally ignored.

What about adding something like a isWarnOnDuplicateKeys() option to log duplicate keys?

```yaml
quarkus:
  banner:
    enabled: false
  banner:
    enabled: true
```
